name: "✈️ Travel/Conference Request"
description: Create a new travel request ticket for a conference, course or workshop
title: "<title>"
labels: ["request","travel"]
body:
  - type: markdown
    attributes:
      value: |
        Exciting! Please share!
  - type: input
    id: start_date
    attributes:
      label: "Start Date"
      description: Start date of the conference/course
      placeholder: "day.month-year"
    validations:
      required: true
  - type: input
    id: end_date
    attributes:
      label: "End Date"
      description: End date of the conference/course
      placeholder: "day.month-year"
    validations:
      required: true
  - type: input
    id: return_date
    attributes:
      label: "Return Date"
      description: Mostly important if weekday,
      placeholder: "day.month-year"
    validations:
      required: false
  - type: textarea
    id: conference_name
    attributes:
      label: "Conference Name"
      description: Conference or course name
      placeholder: "ReactConf2040"
    validations:
      required: true
  - type: textarea
    id: conference_url
    attributes:
      label: "Conference or course URL"
      description: Conference URL
      placeholder: "https://reactconf.com"
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: "Relevance"
      description: Provide a brief explanation of why you have chosen this conference and what you expect to get out of it
      placeholder: Describe in a few lines your request
    validations:
      required: true
  - type: textarea
    id: sharing
    attributes: 
      label: "How will you share what you've learned?"
      description: It is mandatory that you share some of what you've learned with the rest of the team. Do you have any thoughts about how you will do that? If not, you can provide this later.
  - type: textarea
    attributes:
      label: Expected costs
      description: |
        examples:
          | Name       | Cost    |
          |------------|---------|
          | Conference Pass |   $350      |
          | Transport        |   NOK 5000      |
          | Accommodations   |   $1000      |
          | Food             |    $500     |
          |------------|---------|
          | Total             |    Please calculate it in a single currency     |
      value: |
        | Name       | Cost    |
        |------------|---------|
        | Conference Pass |         |
        | Transport        |         |
        | Accommodations   |         |
        | Food             |         |
        |------------|---------|
        | Total             |         |
      render: markdown
    validations:
      required: false
  - type: dropdown
    id: company
    attributes:
      label: Company
      description: Which company do you belong to?
      options:
        - "X"
        - "Flow"
    validations:
      required: true
  - type: dropdown
    id: alone
    attributes:
      label: Mode
      description: Choose a mode?
      options:
        - "Alone"
        - "With a colleague"
        - "With a team"
  - type: textarea
    id: travelingwith
    attributes:
      label: Who are you traveling with?
      description: Only if traveling with others
  - type: checkboxes
    id: isApprovedBy
    attributes:
      label: Tidsrommet er godkjent av
      options:
        - label: Teamleder
        - label: Fagleder
        - label: Prosjektleder
  - type: textarea
    id: additional
    attributes:
      label: Anything else you'd like to say?
      
