name: Initialize travel log
run-name: Reacting to ${{ github.event.issue.title }} by @${{ github.actor }}
on:
  issues:
    types: [labeled, assigned, opened, edited, reopened]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  initialize:
    name: Initialize values for each type
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.values.outputs.branch }}
      filename: ${{ steps.values.outputs.filename }}
      name: ${{ steps.values.outputs.name }}
      title: ${{ steps.values.outputs.title }}
    steps:
      - name: Initialize values and travel log file
        id: values
        run: |
          title=$(echo ${{ github.actor }} goes to ${{ github.event.issue.title }})
          echo "title=$title" >> $GITHUB_OUTPUT
          name=$(echo $title | sed 's/ /-/g' | tr '[:upper:]' '[:lower:]')
          echo "name=$name" >> $GITHUB_OUTPUT
          filename=$(echo $name | sed 's/$/.md/')
          echo "filename=$filename" >> $GITHUB_OUTPUT
          branch='travels/${{ steps.values.outputs.name }}'
          echo "branch=$branch >> $GITHUB_OUTPUT
          echo "Title is $title" >> $GITHUB_STEP_SUMMARY
          echo "Name is $name" >> $GITHUB_STEP_SUMMARY
          echo "Filename is $filename" >> $GITHUB_STEP_SUMMARY
          echo "Branch is $branch" >> $GITHUB_STEP_SUMMARY
  on-event:
    needs: initialize
    name: Create or update pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initialize values and travel log file
        id: values
        run: |
          echo "## ${{ needs.initialize.outputs.title }}" > travel-logs/${{needs.initialize.outputs.filename}}
      - name: Create Issue Branch
        uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ needs.initialize.outputs.branch }}
          title: ${{ needs.initialize.outputs.title }}
          body: ${{ github.event.issue.body }}
          path: "travel-logs"
          commit-message: "docs(${{ github.event.issue.user.name }}): Create travel log"
          labels: ${{ github.event.issue.labels }}
          assignees: ${{ github.event.issue.assignees }}
